config/routes.rb
Rails.application.routes.draw do

  get 'palestras/:id/inscricao', to: 'palestras#inscricao', as: :palestra_incricao
  post 'palestras/:id/inscricao', to: 'palestras#inscricao'
  delete 'cancelamento/:id' , to: 'palestras#cancelamento_inscricao', as: :cancelamento
  
  get 'hotel_pousada/:id/quarto', to: 'quartos#show', as: :detalhe_quarto
  get 'quartos/:id', to: 'quartos#reserva', as: :reserva_cama
  post 'quartos/:id', to: 'quartos#reserva'
  get 'quartos/new/:id' ,to: 'quartos#new', as: :new_quarto
 
  get '/', to: 'users#home', as: :root
  get 'home', to: "users#home", as: :home
  
  get '/evento', to: 'pages#evento', as: :evento
  get '/crud', to: 'pages#crud', as: :crud
  
  get 'federacaos/ranking', to: 'federacaos#ranking', as: :ranking_federacao
  get 'ejs/ranking', to: 'ejs#ranking', as: :ranking_ej
  
  #get 'palestras/:id/arquivos', to: 'arquivos#index', as: :arquivos
  #get 'palestras/:id/arquivos/new', to: 'arquivos#new', as: :new_arquivo
  #post 'palestras/:id/arquivos/new', to: 'arquivos#create'
  #delete 'palestras/destroy/arquivos', to: 'arquivos#destroy', as: :arquivo
  
  resources :hotel_pousadas
  resources :quartos
  resources :palestras
  resources :users
  resources :ejs
  resources :federacaos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :arquivos, only: [:index, :new, :create, :destroy]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #Rotas de SessionsController
  
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  
end

app/models/federacao.rb
class Federacao < ApplicationRecord
  has_many :ejs
  has_many :users
  
end

app/controllers/federacaos_controller.rb
class FederacaosController < ApplicationController
  before_action :set_federacao, only: [:show, :edit, :update, :destroy]

  # GET /federacaos
  # GET /federacaos.json
  def index
    @federacaos = Federacao.all
  end
  
  def ranking
    @federacaos = Federacao.all
  end

  # GET /federacaos/1
  # GET /federacaos/1.json
  def show
  end

  # GET /federacaos/new
  def new
    @federacao = Federacao.new
  end

  # GET /federacaos/1/edit
  def edit
  end

  # POST /federacaos
  # POST /federacaos.json
  def create
    @federacao = Federacao.new(federacao_params)

    respond_to do |format|
      if @federacao.save
        format.html { redirect_to @federacao, notice: 'Federação registrada com suceesso.' }
        format.json { render :show, status: :created, location: @federacao }
      else
        format.html { render :new }
        format.json { render json: @federacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /federacaos/1
  # PATCH/PUT /federacaos/1.json
  def update
    respond_to do |format|
      if @federacao.update(federacao_params)
        format.html { redirect_to @federacao, notice: 'Federação atualizada com suceesso.' }
        format.json { render :show, status: :ok, location: @federacao }
      else
        format.html { render :edit }
        format.json { render json: @federacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /federacaos/1
  # DELETE /federacaos/1.json
  def destroy
    @federacao.destroy
    respond_to do |format|
      format.html { redirect_to federacaos_url, notice: 'Federação removida com suceesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_federacao
      @federacao = Federacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def federacao_params
      params.require(:federacao).permit(:nome, :federada)
    end
end

app/helpers/federacaos_helper.rb
module FederacaosHelper
end

app/views/federacaos/_form.html.erb
<%= form_with(model: federacao, local: true) do |form| %>
  <% if federacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(federacao.errors.count, "error") %> prohibited this federacao from being saved:</h2>

      <ul>
      <% federacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :federacao_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/federacaos/edit.html.erb
<h1>Alterar Federacao</h1>

<%= render 'form', federacao: @federacao %>

<%= link_to 'Mostrar', @federacao %> |
<%= link_to 'Voltar', federacaos_path %>

app/views/federacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Federações</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @federacaos.each do |federacao| %>
      <tr>
        <td><%= federacao.nome %></td>
        <td><%= link_to 'Mostrar', federacao %></td>
        <td><%= link_to 'Editar', edit_federacao_path(federacao) %></td>
        <td><%= link_to 'Remover', federacao, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo registro de Federacao', new_federacao_path %> |
<%= link_to 'Voltar', crud_path %>

app/views/federacaos/new.html.erb
<h1>New Federacao</h1>

<%= render 'form', federacao: @federacao %>

<%= link_to 'Back', federacaos_path %>

app/views/federacaos/ranking.html.erb
<p id="notice"><%= notice %></p>

<h1>Ranking das Empresas Juniores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Federacao</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @federacaos.order(membros: :desc).each do |federacao| %>
      <tr>
        <td><%= federacao.nome %></td>
        <td><%= federacao.membros %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Voltar', home_path %>

app/views/federacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @federacao.nome %>
</p>

<%= link_to 'Editar', edit_federacao_path(@federacao) %> |
<%= link_to 'Voltar', federacaos_path %>