config/routes.rb
Rails.application.routes.draw do

  get 'palestras/:id/inscricao', to: 'palestras#inscricao', as: :palestra_incricao
  post 'palestras/:id/inscricao', to: 'palestras#inscricao'
  delete 'cancelamento/:id' , to: 'palestras#cancelamento_inscricao', as: :cancelamento
  
  get 'hotel_pousada/:id/quarto', to: 'quartos#show', as: :detalhe_quarto
  get 'quartos/:id', to: 'quartos#reserva', as: :reserva_cama
  post 'quartos/:id', to: 'quartos#reserva'
  get 'quartos/new/:id' ,to: 'quartos#new', as: :new_quarto
 
  get '/', to: 'users#home', as: :root
  get 'home', to: "users#home", as: :home
  
  get '/evento', to: 'pages#evento', as: :evento
  get '/crud', to: 'pages#crud', as: :crud
  
  get 'federacaos/ranking', to: 'federacaos#ranking', as: :ranking_federacao
  get 'ejs/ranking', to: 'ejs#ranking', as: :ranking_ej
  
  #get 'palestras/:id/arquivos', to: 'arquivos#index', as: :arquivos
  #get 'palestras/:id/arquivos/new', to: 'arquivos#new', as: :new_arquivo
  #post 'palestras/:id/arquivos/new', to: 'arquivos#create'
  #delete 'palestras/destroy/arquivos', to: 'arquivos#destroy', as: :arquivo
  
  resources :hotel_pousadas
  resources :quartos
  resources :palestras
  resources :users
  resources :ejs
  resources :federacaos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :arquivos, only: [:index, :new, :create, :destroy]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #Rotas de SessionsController
  
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  
end

app/models/ej.rb
class Ej < ApplicationRecord
  belongs_to :federacao
  has_many :users, dependent: :destroy
end

app/controllers/ejs_controller.rb
class EjsController < ApplicationController
  before_action :set_ej, only: [:show, :edit, :update, :destroy]


  def index
    @ejs = Ej.all
  end
  
  def ranking
    @ejs = Ej.all
  end

  def show
  end
  
  def new
    @ej = Ej.new
    @federacaos = Federacao.all
  end

  def edit
    @federacaos = Federacao.all
  end

  def create
    @ej = Ej.new(ej_params)

    respond_to do |format|
      if @ej.save
        format.html { redirect_to @ej, notice: 'Empresa Junior registrada com sucesso.' }
        format.json { render :show, status: :created, location: @ej }
      else
        format.html { render :new }
        format.json { render json: @ej.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ej.update(ej_params)
        format.html { redirect_to @ej, notice: 'Empresa Junior atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @ej }
      else
        format.html { render :edit }
        format.json { render json: @ej.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ej.destroy
    respond_to do |format|
      format.html { redirect_to ejs_url, notice: 'Empresa Junior removida com sucesso.' }
      format.json { head :no_content }
    end
  end
    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ej
      @ej = Ej.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ej_params
      params.require(:ej).permit(:nome, :faculdade, :federacao_id, :user, :federada)
    end
end

app/helpers/ejs_helper.rb
module EjsHelper
end

app/views/ejs/_form.html.erb
<%= form_with(model: ej, local: true) do |form| %>
  <% if ej.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ej.errors.count, "error") %> prohibited this ej from being saved:</h2>

      <ul>
      <% ej.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :ej_nome %>
  </div>

  <div class="field">
    <%= form.label :faculdade %>
    <%= form.text_field :faculdade, id: :ej_faculdade %>
  </div>
  
  <div class="field">
    <%= form.label :Selecione_sua_Federacao %>
    <%= form.select :federacao_id, @federacaos.collect { |federacao| [federacao.nome, federacao.id] }, :prompt => "Sua escolha" %>
  </div>

  <div class="field">
    <%= form.label :federada %>
    <%= form.check_box :federada, id: :federacao_federada %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ejs/edit.html.erb
<h1>Editing Ej</h1>

<%= render 'form', ej: @ej %>

<%= link_to 'Mostrar', @ej %> |
<%= link_to 'Voltar', ejs_path %>

app/views/ejs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empresas Juniores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Faculdade</th>
      <th>Federação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ejs.each do |ej| %>
      <tr>
        <td><%= ej.nome %></td>
        <td><%= ej.faculdade %></td>
        <td><%= ej.federacao.nome %></td>
        <td><%= link_to 'Mostrar', ej %></td>
        <td><%= link_to 'Editar', edit_ej_path(ej) %></td>
        <td><%= link_to 'Remover', ej, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo registro de Empresa Junior', new_ej_path %> |
<%= link_to 'Voltar', crud_path %>

app/views/ejs/new.html.erb
<h1>Novo Registro de Empresa Junior</h1>

<%= render 'form', ej: @ej %>

<%= link_to 'Back', ejs_path %>

app/views/ejs/ranking.html.erb
<p id="notice"><%= notice %></p>

<h1>Ranking das Empresas Juniores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Empresa Junior</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ejs.order(membros: :desc).each do |ej| %>
      <tr>
        <td><%= ej.nome %></td>
        <td><%= ej.membros %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Voltar', home_path %>

app/views/ejs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @ej.nome %>
</p>

<p>
  <strong>Faculdade:</strong>
  <%= @ej.faculdade %>
</p>

<p>
  <strong>Federacao:</strong>
  <%= @ej.federacao.nome %>
</p>

<p>
  <strong>Federada:</strong>
  <%= @ej.federada %>
</p>

<%= link_to 'Edit', edit_ej_path(@ej) %> |
<%= link_to 'Back', ejs_path %>