config/routes.rb
Rails.application.routes.draw do

  get 'palestras/:id/inscricao', to: 'palestras#inscricao', as: :palestra_incricao
  post 'palestras/:id/inscricao', to: 'palestras#inscricao'
  delete 'cancelamento/:id' , to: 'palestras#cancelamento_inscricao', as: :cancelamento
  
  get 'hotel_pousada/:id/quarto', to: 'quartos#show', as: :detalhe_quarto
  get 'quartos/:id', to: 'quartos#reserva', as: :reserva_cama
  post 'quartos/:id', to: 'quartos#reserva'
  get 'quartos/new/:id' ,to: 'quartos#new', as: :new_quarto
 
  get '/', to: 'users#home', as: :root
  get 'home', to: "users#home", as: :home
  
  get '/evento', to: 'pages#evento', as: :evento
  get '/crud', to: 'pages#crud', as: :crud
  
  get 'federacaos/ranking', to: 'federacaos#ranking', as: :ranking_federacao
  get 'ejs/ranking', to: 'ejs#ranking', as: :ranking_ej
  
  #get 'palestras/:id/arquivos', to: 'arquivos#index', as: :arquivos
  #get 'palestras/:id/arquivos/new', to: 'arquivos#new', as: :new_arquivo
  #post 'palestras/:id/arquivos/new', to: 'arquivos#create'
  #delete 'palestras/destroy/arquivos', to: 'arquivos#destroy', as: :arquivo
  
  resources :hotel_pousadas
  resources :quartos
  resources :palestras
  resources :users
  resources :ejs
  resources :federacaos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :arquivos, only: [:index, :new, :create, :destroy]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #Rotas de SessionsController
  
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  
end

app/models/palestra.rb
class Palestra < ApplicationRecord
  belongs_to :user
  
  has_many :inscricaos
  has_many :arquivos, dependent: :destroy
  
  def deliver_mail
    UserMailer.notify_via_email(user, self).deliver_now
  end
  
  
end

app/controllers/palestras_controller.rb
class PalestrasController < ApplicationController
  before_action :palestrante_acc, only: [:edit, :update]
  before_action :normal_user_or_adm, only: [:edit,:update,:destroy]
  before_action :set_palestra, only: [:show, :edit, :update, :destroy, :inscricao, :cancelamento_inscricao]
  before_action :get_palestrantes, only: [:new, :edit]
  before_action :current_user, only: [:inscricao]

  def index
    @palestras = Palestra.paginate(:page => params[:page], :per_page => 4)
  end

  def show
  end

  def new
    @palestra = Palestra.new
    @palestrantes = User.where(palestrante: true)
  end

  def edit
    @palestrantes = User.where(palestrante: true)
  end

  def create
    @palestra = Palestra.new(palestra_params)

    respond_to do |format|
      if @palestra.save
        format.html { redirect_to @palestra, notice: 'Palestra criada.' }
        format.json { render :show, status: :created, location: @palestra }
      else
        format.html { render :new }
        format.json { render json: @palestra.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @palestra.update(palestra_params)
        format.html { redirect_to @palestra, notice: 'Palestra atualizada.' }
        format.json { render :show, status: :ok, location: @palestra }
      else
        format.html { render :edit }
        format.json { render json: @palestra.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @palestra.destroy
    respond_to do |format|
      format.html { redirect_to palestras_url, notice: 'Palestra removida.' }
      format.json { head :no_content }
    end
  end
  
  def inscricao
    @inscription = Inscricao.new
    @inscription.user_id = current_user.id
    @inscription.palestra_id = @palestra.id
    @inscription.save
    Palestra.update(@palestra.id, :vagas => Palestra.find(@palestra.id).vagas-1)
    redirect_to user_path(current_user.id)
  end
  
  def cancelamento_inscricao
    Inscricao.find_by(user_id: current_user, palestra_id: @palestra.id).destroy
    Palestra.update(@palestra.id, :vagas => Palestra.find(@palestra.id).vagas+1)
  
   @palestras = Palestra.where(id: Inscricao.select("palestra_id").where(user_id: current_user.id))
    respond_to do |format|
      format.js {}
      format.html{redirect_to current_user}
      
    end
      
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palestra
      @palestra = Palestra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def palestra_params
      params.require(:palestra).permit(:id, :name, :detalhe, :user_id, :vagas, :dia, :arquivo, :attachment)
    end
    
    def get_palestrantes
      @palestrantes = User.where(palestrante: true)    
    end
    
    def palestrante_acc
      if !current_user.palestrante
        redirect_to palestras_path
      end
    end
end

app/helpers/palestras_helper.rb
module PalestrasHelper
end

app/views/palestras/_form.html.erb
<%= form_with(model: palestra, local: true ,:class => "nova-palestra") do |form|  %>
  <div class="easterEgg">
  <h2>formulario</h2>
  <h2>FILE : palestras/_form.html</h2>
  </div>
  
  <% if palestra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(palestra.errors.count, "error") %> prohibited this palestra from being saved:</h2>

      <ul>
      <% palestra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nome da palestra" %>
    <%= form.text_field :name, id: :palestra_name %>
  </div>
  
  <div class="field">
    <%= form.label "Descrição da palestra" %>
    <%= form.text_area :detalhe, id: :palestra_detalhe %>
  </div>
  
  <div class="field">
    <%= form.label "Quantidade de vagas" %>
    <%= form.text_field :vagas, id: :palestra_vagas %>
  </div>
  
  <div class="field">
    <%= form.label "Dia da palestra" %>
    <%= form.text_field :dia, id: :palestra_dia %>
  </div>

  <div class="field">
    <%= form.label :Selecione_o_Palestrante %>
    <%= form.select :user_id, @palestrantes.collect { |palestrante| [palestrante.nome, palestrante.id] }, :prompt => "Selecione palestrante" %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/palestras/cancelamento_inscricao.js.erb
$("#detalhe-palestras").replaceWith("<%= escape_javascript(render('/users/palestras')) %>");

app/views/palestras/edit.html.erb
<h1>Alterar palestra</h1>

<%= render 'form', palestra: @palestra %>

<%= link_to 'Show', @palestra %> |
<%= link_to 'Back', palestras_path %>

app/views/palestras/index.html.erb
<% provide(:title, "Palestras | Index | ")%>
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <h1>Palestras</h1>
  
  <table id="palestras">
    <thead>
      <tr>
        <th>Quero assistir</th>
        <th>Vagas</th>
        <th>Nome - Assunto</th>
        <th>Detalhe</th>
        <th>Palestrante</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @palestras.each do |palestra| %>
        <tr>
          <td>
            <label class="switch">
              <input type="checkbox" checked>
              <span class="slider round"></span>
            </label>

          </td>
         
          <td><%= palestra.vagas %></td>
          <td><%= palestra.name %></td>
          <td><%= palestra.detalhe %></td>

          <td><strong><%= palestra.user.nome %></strong>
          <br>
          <%= image_tag(palestra.user.photo_url) if palestra.user.photo.present? %>
          </td>
          
          <td>
            <p class="index-palestra"><%= link_to 'Show', palestra %></p>
            <% if current_user.adm || current_user.palestrante %>
              <p class="index-palestra"><%= link_to 'Edit', edit_palestra_path(palestra)%></p>
            <% end %>
            <% if current_user.adm? %>
              <p class="index-palestra destroy"><%= link_to 'Destroy', palestra, method: :delete, data: { confirm: 'Are you sure?' } %></p>
            <% end %>
          </td>
        </tr>
     <% end %>
    </tbody>
  </table>
  <div class="navPag"><%= will_paginate @palestras %></div>
  
        <%= link_to 'Nova Palestra', new_palestra_path %> |
        <%= link_to 'Voltar', home_path %>
</div>

app/views/palestras/new.html.erb
<div class="container">
  <div id="nova-palestra">
  <h1>Nova Palestra</h1>
  <h2>FILE : palestras/new.html</h2>
  
  <%= render 'form', palestra: @palestra %>
  
  <%= link_to 'Back', palestras_path %>
  </div>
</div>

app/views/palestras/show.html.erb
<p id="notice"><%= notice %></p>

<div class="detalhe-palestra">
  <p>
    <strong>Identificador :</strong>
    <%= @palestra.id %>
  </p>
  
  <p>
    <strong>Nome da palestra:</strong>
    <%= @palestra.name %>
  </p>
  <p>
    <strong>Detalhe da palestra:</strong>
    <%= @palestra.detalhe %>
  </p>
  <p>
    <strong>Vagas:</strong>
    <%= @palestra.vagas %>
  </p>
  
  <p>
    <strong>Dia:</strong>
    <%= @palestra.dia %>
  </p>
  
</div>

<div class="palestrante">
  <p><strong>Palestrante: </strong><%= @palestra.user.nome %> <%= @palestra.user.sobrenome %></p>
   <%= image_tag(@palestra.user.photo_url) if @palestra.user.photo.present? %>
</div>

<%= link_to "Arquivos", arquivos_path %> |
 
<%= link_to 'CONFIRMAR INSCRIÇÃO NA PALESTRA', palestra_incricao_path(@palestra) %>
<br>
<br>
<%= link_to 'Editar', edit_palestra_path(@palestra) %> |
<%= link_to 'Voltar', palestras_path %>
</div>