config/routes.rb
Rails.application.routes.draw do

  get 'palestras/:id/inscricao', to: 'palestras#inscricao', as: :palestra_incricao
  post 'palestras/:id/inscricao', to: 'palestras#inscricao'
  delete 'cancelamento/:id' , to: 'palestras#cancelamento_inscricao', as: :cancelamento
  
  get 'hotel_pousada/:id/quarto', to: 'quartos#show', as: :detalhe_quarto
  get 'quartos/:id', to: 'quartos#reserva', as: :reserva_cama
  post 'quartos/:id', to: 'quartos#reserva'
  get 'quartos/new/:id' ,to: 'quartos#new', as: :new_quarto
 
  get '/', to: 'users#home', as: :root
  get 'home', to: "users#home", as: :home
  
  get '/evento', to: 'pages#evento', as: :evento
  get '/crud', to: 'pages#crud', as: :crud
  
  get 'federacaos/ranking', to: 'federacaos#ranking', as: :ranking_federacao
  get 'ejs/ranking', to: 'ejs#ranking', as: :ranking_ej
  
  #get 'palestras/:id/arquivos', to: 'arquivos#index', as: :arquivos
  #get 'palestras/:id/arquivos/new', to: 'arquivos#new', as: :new_arquivo
  #post 'palestras/:id/arquivos/new', to: 'arquivos#create'
  #delete 'palestras/destroy/arquivos', to: 'arquivos#destroy', as: :arquivo
  
  resources :hotel_pousadas
  resources :quartos
  resources :palestras
  resources :users
  resources :ejs
  resources :federacaos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :arquivos, only: [:index, :new, :create, :destroy]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #Rotas de SessionsController
  
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout
  
end

app/models/arquivo.rb
class Arquivo < ApplicationRecord
  belongs_to :palestra
  
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true
end

app/models/cama.rb
class Cama < ApplicationRecord
  belongs_to :quarto
  belongs_to :user
end

app/models/ej.rb
class Ej < ApplicationRecord
  belongs_to :federacao
  has_many :users, dependent: :destroy
end

app/models/federacao.rb
class Federacao < ApplicationRecord
  has_many :ejs
  has_many :users
  
end

app/models/fotos_hotel.rb
class FotosHotel < ApplicationRecord
  mount_uploader :foto, PictureUploader
  
  belongs_to :hotel_pousada
  
end

app/models/hotel_pousada.rb
class HotelPousada < ApplicationRecord

  has_many :quarto
  has_many :fotos_hotel
  
  
end

app/models/inscricao.rb
class Inscricao < ApplicationRecord
  belongs_to :user
  belongs_to :palestra
  
  #after_create :send_activation_email

end

app/models/palestra.rb
class Palestra < ApplicationRecord
  belongs_to :user
  
  has_many :inscricaos
  has_many :arquivos, dependent: :destroy
  
  def deliver_mail
    UserMailer.notify_via_email(user, self).deliver_now
  end
  
  
end

app/models/quarto.rb
class Quarto < ApplicationRecord
  belongs_to :hotel_pousada


end

app/models/user.rb
class User < ApplicationRecord
  has_many :palestras
  has_many :inscricaos, dependent: :destroy
  belongs_to :ej
  
  mount_uploader :photo, PictureUploader
  has_secure_password
  
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :nome, presence: true, length: { in: 3..25 }
  validates :sobrenome, presence: true, length: { in: 2..50 }
  validates :cpf, presence: true, uniqueness: true, length: { in: 10..12 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { in: 10..50 }, format: { with: VALID_EMAIL_REGEX }
  validates :password,presence: true, length: { in: 3..7, presence: true, allow_nil: true }
  validate :picture_size
  
  after_create :send_activation_email
  
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
    
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
  end
  
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  private
  
  def picture_size
    if photo.size > 2.megabytes
      errors.add(:photo, "Imagem não pode ter mais de 2 magabytes")
    end
  end
  
  def downcase_email
    self.email = email.downcase
  end
    
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
  
end

app/helpers/arquivos_helper.rb
module ArquivosHelper
  
  def arquivos
    @arquivos = Arquivo.all
  end
end

app/helpers/ejs_helper.rb
module EjsHelper
end

app/helpers/federacaos_helper.rb
module FederacaosHelper
end

app/helpers/inscricao_helper.rb
module InscricaoHelper
end

app/helpers/inscricaos_helper.rb
module InscricaosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/palestras_helper.rb
module PalestrasHelper
end

app/helpers/quartos_helper.rb
module QuartosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end 
  
  # Se houver alguem logado, retornara o usuario
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  # Se houver alguem logado, retorna true
  def logged_in?
    !current_user.nil?
  end
  
  # Retira o id do usuario logado do cookie de sessao e limpa o current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Redirecionar para o perfil do Usuario, caso o mesmo já esteja logado
  def logged_user
    if logged_in?
      redirect_to user_path(current_user)
    end
  end
  
  # Redirecionar para a página de login se o user não estiver logado
  def non_logged_user
    if !logged_in?
      redirect_to login_path
    end
  end
  
  def normal_user_or_adm
      if current_user != @user && !current_user.adm
        redirect_to user_path(current_user)
      end
  end
  
  def palestrante_acc
      if current_user != @user && !current_user.palestrante
        redirect_to user_path(current_user)
      end
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>Gipsy Avenger</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/png" href="/favicon.png">
  </head>

  <body>
    <h4 class="easterEgg"> FILE : views/layouts/application.html</h1>
    <h4 class="easterEgg"> Isso é o header</h2>
    <% if logged_in?%>
      <header id="loggedHeader">
          <p> <span class="usuer">Olá, <%= current_user.nome %> </span>
            <%= link_to "Logout", logout_path, method: :delete %>
            <%=link_to "Minha conta", user_path(current_user.id) %>
            <%= link_to "Home", home_path %>
            <%= link_to 'Painel do ADM', crud_path if @current_user.adm.present? %>
          </p>
        <div class="cleaning"></div>
      </header>
        <div class="container">
          <div id="homepage">
            <div id="sizing" class="three columns">
              <main id="userMain">
              <div class="foto-usuario"><%= image_tag(@current_user.photo_url) if @current_user.photo.present? %></div>
                <h4><%= @current_user.nome %> <%= @current_user.sobrenome %></h4>
                <h4><%= @current_user.ej.nome %></h4>
                <h4><%= "Administrador" if @current_user.adm.present? %></h4>
                <h4><%= "Palestrante" if @current_user.palestrante.present? %></h4>
              </main>
              <div id="topEJs">
                <h3>Top 5: Empresa Junior</h3>
                <% ejs.each do |ej| %>  
                  <h4><%= ej.nome %></h4>
                <% end %>
              </div>
              <div id="topEJs">
                <h3>Top 5: Federação</h3>
                <% federacaos.each do |federacao| %>  
                  <h4><%= federacao.nome %></h4>
                <% end %>
              </div>
            </div>
          </div>
          <div class="nine columns">
            <nav id="userNav"><ul
              <li><%= link_to 'Home', home_path %></li>
              <li><%= link_to 'O Evento', evento_path %></li>
              <li><%= link_to 'Programação', palestras_path %></li>
              <li><%= link_to 'Acomodações', hotel_pousadas_path %></li>
              <li><a href="#">Transferências</a></li>
            </ul></nav>
            <div id="content">
              <%= yield %>  <!-- CONTEUDO GERAL  -->
            </div>
          </div>
        <% else %>
      <%= yield %>  <!-- CONTEUDO GERAL  -->
    <% end %>
        <div class="cleaning"></div>
      </div>
    </div>
  </body>
</html>

app/views/pages/crud.html.erb
<div class="links">
  <h1>Gerenciar:</h1>
  <%= link_to 'Users', users_path, :class => "navBtn" %><br>
  <%= link_to 'Empresas Juniores', ejs_path, :class => "navBtn" %><br> 
  <%= link_to 'Federações', federacaos_path, :class => "navBtn" %>
</div>

app/views/pages/evento.html.erb
<div class="container">
  <div id="pageEvento">
    <div class="logoEvento"></div>
    <div id="aboutEvento"><p>   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur porta nisi quis pulvinar dictum. Sed lacus quam, pharetra sit amet mi in, varius elementum ex. Suspendisse eleifend eu magna et aliquam. Maecenas lobortis turpis quam, eu fringilla diam ullamcorper ut. Donec eget ligula ac nunc euismod rhoncus eget et elit. Etiam malesuada et ligula ac fermentum. Suspendisse vitae facilisis massa. Nunc elementum varius euismod. Curabitur iaculis turpis volutpat augue eleifend, tempor varius ante dictum. Curabitur elementum risus eu auctor posuere. In fringilla finibus erat a sodales.</p>
    <%= link_to 'Veja a programação completa', palestras_path, :class=>"navBtn" %>
    <%= link_to 'Selecione sua acomodação', hotel_pousadas_path, :class=>"navBtn" %></div>
  </div>  
</div>

app/views/pages/pages.js.erb
$("#foto-usuario").replaceWith("<%= escape_javascript(render('/users/foto_usuario')) %>");